# Generated by Django 5.1.5 on 2026-06-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_detail', to='products.product')),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('warranty', models.IntegerField(default=12, help_text='Warranty in months')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electronics_detail', to='products.product')),
            ],
            options={
                'db_table': 'electronics',
            },
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_detail', to='products.product')),
            ],
            options={
                'db_table': 'fashions',
            },
        ),
    ]
